'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Records', [
      {
        title: 'Example-1',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/e71/e71dcd51ef7ccdcab2a13b1ad5474fc1.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-2',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/922/922a8fb7d8c69d995843d0c525a50904.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-3',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/b0e/b0eaa420a8cde45e6397d00a34ebe8f3.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-4',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/437/437d1cb8ddbbf313df5ae822e15db2a7.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-5',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/e86/e86b328f7f4e8d94c05b1af9b6ab1779.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-6',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/077/0770cc0b9b14204adf076786c0799bbb.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-7',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/03e/03edb77196420eaba8693b72cbb91b82.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-8',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/ea8/ea80d204ccd039489bfa12a68241bc02.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-9',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/b22/b22f7702e95ef7a69dc8823923a4bc78.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Example-10',
        artist: 'Example Artist',
        description: 'Some description',
        img: 'https://stoprobotvinyl.ru/upload/iblock/31f/31f510f936a6865b6587d3cad2e2e887.jpeg',
        quality: 'Mint',
        price: 2999,
        category_id: 1,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Records', null, {});
  },
};
